version: 2
 
sources:
  - name: coffee_shop
    project: aec-students
    dataset: sandpit_louissa  # Hier den Unterordner als Dataset angeben

    tables:
      - name: src_customers
        columns:
          - name: customer_id
            data_tests:
              - unique
              - not_null   
          - name: name
          - name: email
            data_tests: 
              - email_format

      - name: src_order_items
        columns:
          - name: id
          - name: order_id
          - name: product_id

      - name: src_orders
        columns:
          - name: id
          - name: created_at
          - name: customer_id
          - name: total
          - name: address
          - name: state 
          - name: zip

      - name: src_product_prices
        columns:
          - name: id
          - name: product_id
          - name: price
#            data_tests:
#              - value_greater_than_zero:
#                column_name: price
          - name: created_at
          - name: ended_at
#        data_tests:
#          - dbt_utils.mutually_exclusive_ranges:
#              lower_bound_column: created_at
#              upper_bound_column: ended_at
#              partition_by: product_id
#              gaps: not_allowed

      - name: src_pageviews
        columns:
          - name: id
          - name: visitor_id
          - name: device_type
          - name: timestamp
          - name: page
          - name: customer_id 

      - name: src_sample_data_order_items
        columns:
          - name: order_id
          - name: product_id
          - name: customer_id
          - name: product_name
          - name: product_category
          - name: customer_name
          - name: customer_email
          - name: order_stat
          - name: sold_at
          - name: price

      - name: src_form_events
        columns:
          - name: timestamp
          - name: github_username
          - name: event