version: 2
 
sources:
  - name: coffee_shop
    project: aec-students
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
 
